### ISSUE TITLE
Please consider releasing your code under an open source license

### ISSUE THREAD

**Issue by hardebusch** [armrushworth/Teach-Computing-Resources#1]
Hi there,

I’m interested in using your project in a lesson on sorting algorithms, but I noticed that there is no license file or header in your repo. This means that I don’t have any legal permission to use, modify, or distribute your code.

Would it be possible for you to release it under an open source license?

Thanks in advance!

**Comment by ashplaysbass97** [comment]
Sorry it took me a while to get around to it, I've added a license now!
